services:
  - type: web
    name: nexus
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "nexus-deploy.onrender.com,nexus-l8jg.onrender.com,.onrender.com"
