services:
  - type: web
    name: brisoft
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "brisoft-deploy.onrender.com,brisoft-l8jg.onrender.com,.onrender.com"
