# Generated by Django 5.1.2 on 2026-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_sistema_ponto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroponto',
            new_name='core_regist_colabor_e62bd2_idx',
            old_name='ponto_colab_data_idx',
        ),
        migrations.RenameIndex(
            model_name='registroponto',
            new_name='core_regist_data_cea5e6_idx',
            old_name='ponto_data_tipo_idx',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(blank=True, max_length=14, verbose_name='PIS/NIS'),
        ),
    ]
