# Generated by Django 5.1.2 on 2026-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_sistema_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(blank=True, max_length=14, verbose_name='PIS/NIS'),
        ),
    ]
