# Generated by Django 5.1.2 on 2026-03-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_pis_matricula_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_inicial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo na Admissão'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps',
            field=models.CharField(blank=True, max_length=30, verbose_name='CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email_acesso',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Acesso Web'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero_folha',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número da Folha'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ponto_web_foto',
            field=models.BooleanField(default=False, verbose_name='Exige foto na marcação'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ponto_web_inserir',
            field=models.BooleanField(default=False, verbose_name='Permite inserção de pontos'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ponto_web_justificativa',
            field=models.BooleanField(default=False, verbose_name='Permite inserção de justificativas'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ponto_web_permitido',
            field=models.BooleanField(default=False, verbose_name='Permite marcação via Web'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ramal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='superior_direto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='core.colaborador', verbose_name='Superior Direto'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
