# Generated by Django 5.1.2 on 2026-03-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rh_colaborador_campos_brisoftid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('cei', models.CharField(blank=True, max_length=30, verbose_name='CEI')),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('numero_folha', models.CharField(blank=True, max_length=30, verbose_name='Número da Folha')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('fluxo_aprovacao', models.CharField(blank=True, max_length=100, verbose_name='Fluxo de Aprovação')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável')),
                ('responsavel_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo do Responsável')),
                ('responsavel_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Responsável')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
