# Generated by Django 5.1.2 on 2026-03-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_add_empresa_fk_to_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fluxo_aprovacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fluxo de Aprovação'),
        ),
    ]
