# Generated by Django 5.1.2 on 2026-03-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_add_empresa_fk_to_colaborador'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroponto',
            new_name='core_regist_colabor_e62bd2_idx',
            old_name='ponto_colab_data_idx',
        ),
        migrations.RenameIndex(
            model_name='registroponto',
            new_name='core_regist_data_cea5e6_idx',
            old_name='ponto_data_tipo_idx',
        ),
    ]
