# Generated by Django 5.1.2 on 2026-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_department_fluxo_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='Exibir no Menu de Navegação'),
        ),
    ]
