# Generated by Django 5.1.2 on 2026-03-19 20:01

from django.db import migrations


def seed_functional_departments(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    functional_slugs = ['nrs-suporte', 'cs-clientes', 'rh', 'nrp', 'onboarding', 'logistica']
    Department.objects.filter(slug__in=functional_slugs).update(show_in_nav=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_department_show_in_nav'),
    ]

    operations = [
        migrations.RunPython(seed_functional_departments),
    ]
