# Generated by Django 5.1.2 on 2026-03-19 20:01

from django.db import migrations


def seed_functional_departments(apps, schema_editor):
    # Apenas os departamentos oficiais do sistema devem aparecer no menu.
    # Departamentos legados (CS Clientes, NRS Suporte, RH, NRP, Onboarding, Logística)
    # são deletados em migrations posteriores e não devem ser ativados.
    Department = apps.get_model('core', 'Department')
    official_slugs = ['escala', 'ponto-eletronico']
    Department.objects.filter(slug__in=official_slugs).update(show_in_nav=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_department_show_in_nav'),
    ]

    operations = [
        migrations.RunPython(seed_functional_departments),
    ]
