# Generated by Django 5.1.2 on 2026-03-19 20:19

from django.db import migrations, connection

def create_cargo_table(apps, schema_editor):
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS core_cargo (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                nome VARCHAR(100) NOT NULL,
                salario_base DECIMAL(10, 2),
                descricao TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                department_id BIGINT NOT NULL REFERENCES core_department(id) ON DELETE CASCADE
            );
            """)
        else:
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS core_cargo (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome VARCHAR(100) NOT NULL,
                salario_base DECIMAL(10, 2),
                descricao TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                department_id BIGINT NOT NULL REFERENCES core_department(id) ON DELETE CASCADE
            );
            """)

def drop_cargo_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS core_cargo;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_seed_functional_departments'),
    ]

    operations = [
        migrations.RunPython(create_cargo_table, drop_cargo_table),
    ]
