# Generated by Django 5.1.2 on 2026-03-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_seed_functional_departments'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS core_cargo (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                nome VARCHAR(100) NOT NULL,
                salario_base DECIMAL(10, 2),
                descricao TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                department_id BIGINT NOT NULL REFERENCES core_department(id) ON DELETE CASCADE
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS core_cargo;"
        ),
    ]
