# Generated by Django 5.1.2 on 2026-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='apply_to_all',
            field=models.BooleanField(default=True, verbose_name='Todos os Funcionários'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='target_companies',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='core.empresa', verbose_name='Empresas'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='core.department', verbose_name='Departamentos'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='target_turnos',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='core.turno', verbose_name='Horários'),
        ),
    ]
