# Generated by Django 5.1.2 on 2026-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_holiday_apply_to_all_holiday_target_companies_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['nome_completo'], name='core_colabo_nome_co_4b7699_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['department'], name='core_colabo_departm_777752_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['empresa'], name='core_colabo_empresa_158501_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['status'], name='core_colabo_status_799645_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome'], name='core_empres_nome_1a6585_idx'),
        ),
    ]
