# Generated by Django 5.1.2 on 2026-03-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_colaborador_core_colabo_nome_co_4b7699_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Justificativa')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('abonar', models.BooleanField(default=True, verbose_name='Abona Horas?')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Justificativa',
                'verbose_name_plural': 'Tipos de Justificativa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('trabalho', 'Trabalho (Regular)'), ('folga', 'Folga'), ('neutro', 'Dia Neutro'), ('compensado', 'Compensado'), ('almoço_livre', 'Almoço Livre'), ('afastamento', 'Afastamento/Atestado')], default='trabalho', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_mensais', to='core.colaborador')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_mensais', to='core.turno')),
                ('justificativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.justificativaponto')),
            ],
            options={
                'verbose_name': 'Escala Mensal',
                'verbose_name_plural': 'Escalas Mensais',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['colaborador', 'data'], name='core_escala_colabor_c223fc_idx')],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
