# Generated by Django 5.1.2 on 2026-03-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_justificativaponto_escalamensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('ciclico', 'Cíclico'), ('jornada', 'Jornada')], default='semanal', max_length=20)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('cor', models.CharField(default='#2563eb', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('dias_ciclo', models.IntegerField(blank=True, null=True)),
                ('folga_nos_intervalos', models.BooleanField(default=False, verbose_name='Folga nos Intervalos (não refeição)')),
                ('almoço_livre_global', models.BooleanField(default=False)),
                ('compensado_global', models.BooleanField(default=False)),
                ('neutro_global', models.BooleanField(default=False)),
                ('tol_entrada', models.IntegerField(default=5)),
                ('tol_saida', models.IntegerField(default=5)),
                ('tol_intervalo', models.IntegerField(default=5)),
                ('tol_diaria', models.IntegerField(default=10)),
                ('dia_dsr', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], default=6)),
                ('minimo_horas_dsr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descontar_faltas_dsr', models.BooleanField(default=True)),
                ('utiliza_banco_horas', models.BooleanField(default=False)),
                ('modo_extra', models.CharField(choices=[('simples', 'Simples'), ('avançado', 'Avançado')], default='simples', max_length=20)),
                ('percentual_diurno', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('percentual_noturno', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('inicio_noturno', models.TimeField(default='22:00')),
                ('fim_noturno', models.TimeField(default='05:00')),
                ('fator_noturno', models.IntegerField(default=60)),
                ('fechamento_noturno_global', models.TimeField(default='00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='escalamensal',
            name='turno',
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='horario_previsto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_mensais', to='core.horario'),
        ),
        migrations.CreateModel(
            name='HorarioDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_index', models.IntegerField()),
                ('nome_dia', models.CharField(blank=True, max_length=20)),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('saida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('saida_2', models.TimeField(blank=True, null=True)),
                ('total_horas', models.CharField(default='00:00', max_length=10)),
                ('almoco_livre', models.BooleanField(default=False)),
                ('compensado', models.BooleanField(default=False)),
                ('neutro', models.BooleanField(default=False)),
                ('fechamento_noturno', models.TimeField(default='00:00')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='core.horario')),
            ],
            options={
                'ordering': ['dia_index'],
                'unique_together': {('horario', 'dia_index')},
            },
        ),
    ]
