# Generated by Django 5.1.2 on 2026-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_horario_remove_escalamensal_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='modo_extra',
            field=models.CharField(choices=[('simples', 'Simples (Diário)'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('avançado', 'Avançado')], default='simples', max_length=20),
        ),
    ]
