# Generated by Django 5.1.2 on 2026-03-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_horario_modo_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='considera_atraso_fim',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_atraso_inicio',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_atraso_intervalo',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_extra_antes',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_extra_depois',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_extra_intervalo',
            field=models.CharField(blank=True, default='considera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='considera_extra_intervalo_curto',
            field=models.CharField(blank=True, default='minutos_trabalhados', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='inicio_mes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='modo_compensacao',
            field=models.CharField(blank=True, default='sem_compensacao', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='pre_assinalar',
            field=models.CharField(blank=True, default='sem_marcacao', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='quando_domingo',
            field=models.CharField(blank=True, default='extra', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='quando_feriado',
            field=models.CharField(blank=True, default='extra', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='refeicao_tipo',
            field=models.CharField(blank=True, default='s1_e2', max_length=50, null=True),
        ),
    ]
