# Generated by Django 5.1.2 on 2026-03-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_horario_considera_atraso_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='descontar_tol_extras',
            field=models.CharField(blank=True, default='nunca_desconta', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='descontar_tol_faltas',
            field=models.CharField(blank=True, default='nunca_desconta', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='desconto_dsr_feriado',
            field=models.CharField(blank=True, default='desconta_normais', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='limite_extra_diario',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='horario',
            name='limite_falta_diario',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='horario',
            name='max_faltas_dsr',
            field=models.CharField(default='02:00', max_length=10),
        ),
        migrations.AddField(
            model_name='horario',
            name='primeiro_dia_semana',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='quando_limite_extra',
            field=models.CharField(blank=True, default='considera_tudo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='quando_limite_falta',
            field=models.CharField(blank=True, default='considera_tudo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='tempo_dsr',
            field=models.CharField(default='07:20', max_length=10),
        ),
        migrations.AddField(
            model_name='horario',
            name='tol_clt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='tol_extra_batida',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='tol_falta_batida',
            field=models.IntegerField(default=5),
        ),
    ]
