# Generated by Django 5.2.12 on 2026-03-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_horario_descontar_tol_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='perc_extra_dia_diurno',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_dia_noturno',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_dom_diurno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_dom_noturno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_feriado_diurno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_feriado_noturno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_sab_diurno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_sab_noturno',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.CreateModel(
            name='PoliticaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('dias', models.CharField(default='qualquer_dia', max_length=100)),
                ('feriado', models.CharField(default='qualquer', max_length=100)),
                ('noturno', models.CharField(default='ambos', max_length=100)),
                ('intervalo', models.CharField(default='tudo', max_length=100)),
                ('dia_especifico', models.CharField(default='qualquer', max_length=100)),
                ('acumulo', models.CharField(default='diario', max_length=100)),
                ('eventos', models.CharField(blank=True, max_length=100)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_hora_extra', to='core.horario')),
            ],
            options={
                'verbose_name': 'Política de Hora Extra',
                'verbose_name_plural': 'Políticas de Hora Extra',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='FaixaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ate_horas', models.DecimalField(decimal_places=2, default=24, max_digits=5)),
                ('acrescimo_percentual', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('banco_horas', models.BooleanField(default=True)),
                ('codigo_evento', models.CharField(blank=True, max_length=50)),
                ('codigo_evento_acrescimo', models.CharField(blank=True, max_length=50)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='core.politicahoraextra')),
            ],
            options={
                'verbose_name': 'Faixa de Hora Extra',
                'verbose_name_plural': 'Faixas de Hora Extra',
                'ordering': ['de_horas'],
            },
        ),
    ]
