# Generated by Django 5.2.12 on 2026-03-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_horario_perc_extra_dia_diurno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='calculo_extra_interjornada',
            field=models.CharField(blank=True, default='nao_calcula', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='desconto_faltas_extras',
            field=models.CharField(blank=True, default='desconta_maior', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='folgas_semana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='modo_neutro',
            field=models.CharField(blank=True, default='desconsidera_faltas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='perc_extra_interjornada',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, null=True),
        ),
    ]
