# Generated by Django 5.2.12 on 2026-03-21 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_horario_calculo_extra_interjornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualColunaApuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='bi-layout-text-window', max_length=50)),
                ('colunas', models.JSONField(default=list)),
                ('padrao', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuais_apuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-padrao', 'nome'],
            },
        ),
    ]
