# Generated by Django 5.1.2 on 2026-03-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_visualcolunaapuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='horario_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_vinculados', to='core.horario'),
        ),
    ]
