# Generated by Django 5.1.2 on 2026-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_colaborador_horario_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamensal',
            name='is_almoco_livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='is_compensado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='is_folga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='is_neutro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
