# Generated by Django 5.1.2 on 2026-03-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_escalamensal_is_almoco_livre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInconsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campo', models.CharField(choices=[('atraso', 'Horas Atraso'), ('falta', 'Dia de Falta'), ('extra_total', 'Extras Total'), ('banco_pos', 'Banco Positivo'), ('banco_neg', 'Banco Negativo'), ('intervalo_curto', 'Intervalo Curto'), ('interjornada', 'Interjornada'), ('marcacoes_impares', 'Marcações Ímpares')], max_length=30)),
                ('tolerancia', models.IntegerField(default=1, help_text='A partir de quantos minutos disparar?')),
                ('prioridade', models.IntegerField(default=5)),
                ('icone', models.CharField(default='bi-exclamation-circle-fill', max_length=100)),
                ('cor', models.CharField(default='#dc3545', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Inconsistência',
                'verbose_name_plural': 'Tipos de Inconsistência',
                'ordering': ['prioridade', 'nome'],
            },
        ),
    ]
