# Generated by Django 5.1.2 on 2026-03-31 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_tipoinconsistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaponto',
            name='abonar_dia_falta',
            field=models.BooleanField(default=True, verbose_name='Abonar dia faltoso?'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='abreviacao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Abreviação'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='descontar_dsr',
            field=models.BooleanField(default=False, verbose_name='Descontar DSR?'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='informar_cid',
            field=models.BooleanField(default=False, verbose_name='Informar CID ao lançar a justificativa'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='mostrar_em_coluna',
            field=models.CharField(default='apenas_justificar', max_length=50, verbose_name='Coluna para mostrar'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='pedir_texto_motivo',
            field=models.BooleanField(default=True, verbose_name='Pedir texto de motivo a cada lançamento'),
        ),
        migrations.AddField(
            model_name='justificativaponto',
            name='tipo',
            field=models.CharField(choices=[('dia_inteiro', 'Justificar dia inteiro'), ('periodo_especifico', 'Período Específico'), ('abonar_horas', 'Abonar quantidade de horas'), ('ajustar_horas', 'Ajustar quantidade de horas'), ('relocar_extrafalta', 'Relocar extra/falta do dia'), ('abonar_dsr', 'Abonar apenas DSR (não a ausência)')], default='periodo_especifico', max_length=30),
        ),
        migrations.AlterField(
            model_name='justificativaponto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome/Descrição'),
        ),
        migrations.CreateModel(
            name='LancamentoJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Início')),
                ('data_fim', models.DateField(verbose_name='Data Término')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora Término')),
                ('motivo_texto', models.TextField(blank=True, verbose_name='Texto Justificativa')),
                ('cid', models.CharField(blank=True, max_length=20, verbose_name='CID')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_lancadas', to='core.colaborador')),
                ('justificativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.justificativaponto')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento de Justificativa',
                'verbose_name_plural': 'Lançamentos de Justificativas',
                'ordering': ['-data_inicio', '-hora_inicio'],
                'indexes': [models.Index(fields=['colaborador', 'data_inicio'], name='core_lancam_colabor_d613f2_idx')],
            },
        ),
    ]
