# Generated by Django 5.1.2 on 2026-04-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_justificativaponto_abonar_dia_falta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='considerar_feriados_ponto',
            field=models.BooleanField(default=True, verbose_name='Considerar Feriados no Ponto'),
        ),
        migrations.CreateModel(
            name='TrocaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_feriado', models.DateField(verbose_name='Data Original do Feriado')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Feriado')),
                ('data_troca', models.DateField(verbose_name='Trocado para')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_feriados', to='core.empresa')),
                ('horarios_beneficiados', models.ManyToManyField(blank=True, to='core.horario', verbose_name='Horários Beneficiados')),
            ],
            options={
                'verbose_name': 'Troca de Feriado',
                'verbose_name_plural': 'Trocas de Feriado',
                'ordering': ['-data_feriado'],
            },
        ),
    ]
