# Generated by Django 5.1.2 on 2026-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_empresa_considerar_feriados_ponto_trocaferiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trocaferiado',
            name='repete_anualmente',
            field=models.BooleanField(default=False, verbose_name='Repete Troca Anualmente'),
        ),
    ]
