# Generated by Django 5.1.2 on 2026-04-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_complaint_ia_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrisoftIABase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_articles', to='core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Artigo da Base Brisoft IA',
                'verbose_name_plural': 'Artigos da Base Brisoft IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
