# Generated by Django 6.0.5 on 2026-05-05 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_adiciona_base_auditoria_e_campos_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analistaescala',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_perfis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EscalaRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rascunhos_escala', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rascunho de Escala',
                'verbose_name_plural': 'Rascunhos de Escala',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analistaescala',
            name='rascunho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analistas', to='core.escalarascunho'),
        ),
        migrations.AddField(
            model_name='folgamanual',
            name='rascunho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folgas', to='core.escalarascunho'),
        ),
        migrations.AddField(
            model_name='turno',
            name='rascunho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.escalarascunho'),
        ),
    ]
