# Generated by Django 5.1.2 on 2026-05-06 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_analistaescala_user_escalarascunho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_trabalhados', models.IntegerField(default=5)),
                ('dias_folga', models.IntegerField(default=2)),
                ('tipo', models.CharField(choices=[('fixa', 'Fixa'), ('rotativa', 'Rotativa')], default='fixa', max_length=20)),
                ('permite_fim_de_semana', models.BooleanField(default=True, verbose_name='Permitir Finais de Semana')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Escala',
                'verbose_name_plural': 'Modelos de Escala',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modelo_escala_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeloescala')),
            ],
            options={
                'verbose_name': 'Configuração de Escala',
                'verbose_name_plural': 'Configurações de Escala',
            },
        ),
        migrations.AddField(
            model_name='analistaescala',
            name='modelo_escala',
            field=models.ForeignKey(blank=True, help_text='Override do modelo de escala do rascunho/principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analistas', to='core.modeloescala'),
        ),
        migrations.AddField(
            model_name='escalarascunho',
            name='modelo_escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos', to='core.modeloescala'),
        ),
    ]
