# Generated by Django 5.1.2 on 2026-05-08 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_modeloescala_configuracaoescala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('propria', 'Troca de Folga Própria'), ('analista', 'Troca com Analista')], max_length=20)),
                ('data_solicitante', models.DateField()),
                ('data_receptor', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente_analista', 'Aguardando Analista'), ('pendente_gestor', 'Aguardando Gestor'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente_gestor', max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('aprovado_receptor_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_gestor_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_gestor_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_aprovadas_gestor', to=settings.AUTH_USER_MODEL)),
                ('rascunho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trocas_folga', to='core.escalarascunho')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_recebidas', to='core.analistaescala')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_solicitadas', to='core.analistaescala')),
            ],
            options={
                'verbose_name': 'Troca de Folga',
                'verbose_name_plural': 'Trocas de Folga',
                'ordering': ['-created_at'],
            },
        ),
    ]
