# Generated by Django 5.1.2 on 2026-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_add_troca_folga'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='min_analistas',
            field=models.IntegerField(default=0, help_text='Número mínimo de analistas ativos exigido no turno. 0 = sem restrição.'),
        ),
    ]
