# Generated by Django 5.1.2 on 2026-05-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_add_turno_min_analistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigobaseconhecimento',
            name='votos_inuteis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artigobaseconhecimento',
            name='votos_uteis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
