# Generated by Django 5.1.2 on 2026-05-11 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_artigobaseconhecimento_votos_inuteis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('avulsa', 'Folga Avulsa'), ('banco', 'Folga Banco de Horas'), ('outros', 'Outros')], max_length=20)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('pendente_gestor', 'Aguardando Gestor'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente_gestor', max_length=30)),
                ('aprovado_gestor_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_folga', to='core.analistaescala')),
                ('aprovado_gestor_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folgas_solicitadas_aprovadas_gestor', to=settings.AUTH_USER_MODEL)),
                ('rascunho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_folga', to='core.escalarascunho')),
            ],
            options={
                'verbose_name': 'Solicitação de Folga',
                'verbose_name_plural': 'Solicitações de Folga',
                'ordering': ['-created_at'],
            },
        ),
    ]
