# Generated by Django 5.1.2 on 2026-05-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_solicitacaofolga'),
    ]

    operations = [
        migrations.AddField(
            model_name='analistaescala',
            name='escala_tipo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('gestao', 'Gestão')], default='operacional', max_length=20, verbose_name='Tipo de Escala'),
        ),
        migrations.AddField(
            model_name='configuracaoescala',
            name='modelo_escala_principal_gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_gestao', to='core.modeloescala', verbose_name='Modelo Principal (Gestão)'),
        ),
        migrations.AddField(
            model_name='escalarascunho',
            name='escala_tipo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('gestao', 'Gestão')], default='operacional', max_length=20, verbose_name='Tipo de Escala'),
        ),
        migrations.AddField(
            model_name='turno',
            name='escala_tipo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('gestao', 'Gestão')], default='operacional', max_length=20, verbose_name='Tipo de Escala'),
        ),
        migrations.AlterField(
            model_name='configuracaoescala',
            name='modelo_escala_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_operacional', to='core.modeloescala'),
        ),
    ]
