# Generated by Django 5.1.7 on 2026-05-25 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_add_escala_tipo_gestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.department'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Reset de Senha'), ('status_change', 'Mudança de Status'), ('admin_action', 'Ação Administrativa'), ('financial_action', 'Ação Financeira'), ('permission_change', 'Alteração de Permissões'), ('export_data', 'Exportação de Dados'), ('ai_usage', 'Uso de IA')], max_length=50),
        ),
        migrations.CreateModel(
            name='IAConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_consumptions', to='core.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IAQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=100)),
                ('monthly_limit', models.IntegerField(default=3000)),
                ('alert_threshold_percent', models.IntegerField(default=80)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ia_quota', to='core.department')),
            ],
        ),
    ]
