# Generated by Django 5.1.7 on 2026-05-26 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auditlog_ip_address_auditlog_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_temporarios', to='core.analistaescala')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_temporarios_aprovados', to=settings.AUTH_USER_MODEL)),
                ('rascunho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_temporarios', to='core.escalarascunho')),
                ('turno_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_substituidos', to='core.turno')),
                ('turno_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_temporarios_aplicados', to='core.turno')),
            ],
            options={
                'verbose_name': 'Jornada Temporária',
                'verbose_name_plural': 'Jornadas Temporárias',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
