# Generated by Django 5.1.7 on 2026-06-08 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auditlog_ip_address_auditlog_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloescala',
            name='ciclo_personalizado',
            field=models.JSONField(blank=True, help_text='Padrão semanal de folgas para escala personalizada (JSON)', null=True, verbose_name='Ciclo Personalizado'),
        ),
        migrations.AlterField(
            model_name='modeloescala',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('rotativa', 'Rotativa'), ('personalizado', 'Personalizado')], default='fixa', max_length=20),
        ),
        migrations.CreateModel(
            name='EscalaPersonalizadaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados_template', models.JSONField(help_text='Dicionário {"DD": "status"} com padrão de um mês de referência', verbose_name='Dados do Template')),
                ('total_folgas', models.IntegerField(default=0, verbose_name='Total de Folgas')),
                ('total_trabalho', models.IntegerField(default=0, verbose_name='Total de Trabalho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_escala_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Escala Personalizada',
                'verbose_name_plural': 'Templates de Escala Personalizada',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EscalaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('dados', models.JSONField(default=dict, help_text='Dicionário {"YYYY-MM-DD": "status"} definindo cada dia do mês', verbose_name='Dados do Mês')),
                ('modo_teste', models.BooleanField(default=False, help_text='Se marcado, esse mês não afeta a escala publicada e serve apenas para simulação', verbose_name='Modo Teste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_personalizadas', to='core.analistaescala')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_personalizadas_criadas', to=settings.AUTH_USER_MODEL)),
                ('rascunho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_personalizadas', to='core.escalarascunho')),
            ],
            options={
                'verbose_name': 'Escala Personalizada',
                'verbose_name_plural': 'Escalas Personalizadas',
                'ordering': ['ano', 'mes', 'analista'],
                'indexes': [models.Index(fields=['analista', 'ano', 'mes'], name='core_escala_analist_fcf110_idx'), models.Index(fields=['rascunho', 'ano', 'mes'], name='core_escala_rascunh_6dc68b_idx')],
                'unique_together': {('analista', 'rascunho', 'ano', 'mes')},
            },
        ),
    ]
