# Generated by Django 5.1.7 on 2026-06-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_escala_personalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequestattachment',
            name='refund_request',
        ),
        migrations.RemoveField(
            model_name='refundrequestattachment',
            name='uploaded_by',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='brisoftiabase',
                    table='core_nexusiabase',
                ),
            ],
            database_operations=[]
        ),
        migrations.DeleteModel(
            name='RefundRequest',
        ),
        migrations.DeleteModel(
            name='RefundRequestAttachment',
        ),
    ]
