# Generated by Django 5.1.7 on 2026-06-09 23:10

from django.db import migrations


def remove_rh_department(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    User = apps.get_model('core', 'User')
    nrs_suporte = Department.objects.filter(slug='nrs-suporte').first()
    rh = Department.objects.filter(slug='rh').first()
    if rh:
        if nrs_suporte:
            User.objects.filter(department=rh).update(department=nrs_suporte)
        rh.delete()


def reverse_remove_rh_department(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    Department.objects.get_or_create(
        slug='rh',
        defaults={'name': 'RH', 'description': 'Recursos Humanos'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_remove_cs_clientes_department'),
    ]

    operations = [
        # Primeiro: remover unique_together ANTES de remover os campos
        migrations.AlterUniqueTogether(
            name='escalamensal',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='horariodetalhe',
            unique_together=None,
        ),
        # Remover FKs de BancoHoras
        migrations.RemoveField(
            model_name='bancohoras',
            name='colaborador',
        ),
        # Remover FKs de Cargo
        migrations.RemoveField(
            model_name='cargo',
            name='department',
        ),
        # Remover FKs de Colaborador
        migrations.RemoveField(
            model_name='colaborador',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='department',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='horario_padrao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='superior_direto',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='user',
        ),
        # Remover FKs de EscalaMensal
        migrations.RemoveField(
            model_name='escalamensal',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='escalamensal',
            name='horario_previsto',
        ),
        migrations.RemoveField(
            model_name='escalamensal',
            name='justificativa',
        ),
        # Remover FKs de PerformanceRH
        migrations.RemoveField(
            model_name='performancerh',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='performancerh',
            name='avaliador',
        ),
        # Remover FKs de DocumentoColaborador
        migrations.RemoveField(
            model_name='documentocolaborador',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='documentocolaborador',
            name='uploaded_by',
        ),
        # Remover FKs de RegistroPonto
        migrations.RemoveField(
            model_name='registroponto',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='registrado_por',
        ),
        # Remover FKs de HistoricoProfissional
        migrations.RemoveField(
            model_name='historicoprofissional',
            name='colaborador',
        ),
        # Remover FKs de LancamentoJustificativa
        migrations.RemoveField(
            model_name='lancamentojustificativa',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='lancamentojustificativa',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='lancamentojustificativa',
            name='lancado_por',
        ),
        # Remover FKs de ConfiguracaoPonto
        migrations.RemoveField(
            model_name='configuracaoponto',
            name='department',
        ),
        # Remover FKs de Holiday
        migrations.RemoveField(
            model_name='holiday',
            name='target_companies',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='target_departments',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='target_turnos',
        ),
        # Remover FKs de TrocaFeriado
        migrations.RemoveField(
            model_name='trocaferiado',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='trocaferiado',
            name='horarios_beneficiados',
        ),
        # Remover FKs de FaixaHoraExtra
        migrations.RemoveField(
            model_name='faixahoraextra',
            name='politica',
        ),
        # Remover FKs de HorarioDetalhe
        migrations.RemoveField(
            model_name='horariodetalhe',
            name='horario',
        ),
        # Remover FKs de PoliticaHoraExtra
        migrations.RemoveField(
            model_name='politicahoraextra',
            name='horario',
        ),
        # Remover FKs de VisualColunaApuracao
        migrations.RemoveField(
            model_name='visualcolunaapuracao',
            name='usuario',
        ),
        # Deletar todos os modelos RH
        migrations.DeleteModel(
            name='TipoInconsistencia',
        ),
        migrations.DeleteModel(
            name='BancoHoras',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='CentroCusto',
        ),
        migrations.DeleteModel(
            name='HistoricoProfissional',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoPonto',
        ),
        migrations.DeleteModel(
            name='DocumentoColaborador',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='EscalaMensal',
        ),
        migrations.DeleteModel(
            name='FaixaHoraExtra',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='HorarioDetalhe',
        ),
        migrations.DeleteModel(
            name='TrocaFeriado',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='PoliticaHoraExtra',
        ),
        migrations.DeleteModel(
            name='JustificativaPonto',
        ),
        migrations.DeleteModel(
            name='LancamentoJustificativa',
        ),
        migrations.DeleteModel(
            name='PerformanceRH',
        ),
        migrations.DeleteModel(
            name='RegistroPonto',
        ),
        migrations.DeleteModel(
            name='VisualColunaApuracao',
        ),
        # Remover departamento RH do banco de dados
        migrations.RunPython(remove_rh_department, reverse_code=reverse_remove_rh_department),
    ]
