# Generated by Django 5.1.7 on 2026-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_analystassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acesso_escala',
            field=models.BooleanField(default=False, verbose_name='Acesso Escala'),
        ),
        migrations.AddField(
            model_name='user',
            name='acesso_ponto',
            field=models.BooleanField(default=False, verbose_name='Acesso Ponto Eletrônico'),
        ),
    ]
