# Generated by Django 5.1.7 on 2026-06-10 17:07

from django.db import migrations


def migrate_departments_and_permissions(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    User = apps.get_model('core', 'User')

    # 1. Renomear "RH" para "Ponto Eletrônico" e ajustar slug
    rh_depts = Department.objects.filter(name__iexact='RH')
    for dept in rh_depts:
        dept.name = 'Ponto Eletrônico'
        dept.slug = 'ponto-eletronico'
        dept.show_in_nav = True
        dept.save()
        
    if not rh_depts.exists():
        if not Department.objects.filter(name__iexact='Ponto Eletrônico').exists():
            Department.objects.create(name='Ponto Eletrônico', slug='ponto-eletronico', show_in_nav=True)

    # 2. Renomear "NRS Suporte" para "Escala" e ajustar slug
    nrs_depts = Department.objects.filter(name__iexact='NRS Suporte')
    for dept in nrs_depts:
        dept.name = 'Escala'
        dept.slug = 'escala'
        dept.show_in_nav = True
        dept.save()
        
    if not nrs_depts.exists():
        if not Department.objects.filter(name__iexact='Escala').exists():
            Department.objects.create(name='Escala', slug='escala', show_in_nav=True)

    # 3. Remover do menu de navegação os departamentos: CS Clientes, Logística, NRP, Onboarding
    depts_to_hide = ['CS Clientes', 'Logística', 'NRP', 'Onboarding']
    for dept_name in depts_to_hide:
        Department.objects.filter(name__iexact=dept_name).update(show_in_nav=False)

    # 4. Migrar permissões dos usuários
    # Quem é do depto de Escala (antigo NRS Suporte ou atual Escala) ganha acesso_escala = True
    dept_escala = Department.objects.filter(name='Escala').first()
    if dept_escala:
        User.objects.filter(department=dept_escala).update(acesso_escala=True)

    # Quem é do depto de Ponto Eletrônico (antigo RH ou atual Ponto Eletrônico) ganha acesso_ponto = True
    dept_ponto = Department.objects.filter(name='Ponto Eletrônico').first()
    if dept_ponto:
        User.objects.filter(department=dept_ponto).update(acesso_ponto=True)

    # Administradores têm acesso a tudo
    User.objects.filter(role='administrador').update(acesso_escala=True, acesso_ponto=True)


def rollback_departments_and_permissions(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    Department.objects.filter(name='Ponto Eletrônico').update(name='RH', slug='rh')
    Department.objects.filter(name='Escala').update(name='NRS Suporte', slug='nrs-suporte')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_user_acesso_escala_user_acesso_ponto'),
    ]

    operations = [
        migrations.RunPython(migrate_departments_and_permissions, rollback_departments_and_permissions),
    ]

