# Generated by Django 5.1.7 on 2026-06-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_migrate_access_and_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinactivityrequest',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='chatinactivityrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='analista',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='department',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='routinelog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routinelog',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ChatInactivityRequest',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='RoutineLog',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
