# Generated by Django 5.1.7 on 2026-06-10 18:23

from django.db import migrations

def delete_legacy_departments(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    User = apps.get_model('core', 'User')

    # Garantir que 'Escala' e 'Ponto Eletrônico' existam
    escala, _ = Department.objects.get_or_create(slug='escala', defaults={'name': 'Escala', 'description': 'Escala de Trabalho', 'show_in_nav': True})
    ponto, _ = Department.objects.get_or_create(slug='ponto-eletronico', defaults={'name': 'Ponto Eletrônico', 'description': 'Ponto Eletrônico', 'show_in_nav': True})

    # Consolidar qualquer usuário de departamentos não oficiais para None
    User.objects.exclude(department__slug__in=['escala', 'ponto-eletronico']).update(department=None)

    # Deletar fisicamente do banco todos os departamentos legados
    depts_to_delete = ['CS Clientes', 'Logística', 'NRP', 'NRS Suporte', 'Onboarding', 'RH']
    Department.objects.filter(name__in=depts_to_delete).delete()
    Department.objects.exclude(slug__in=['escala', 'ponto-eletronico']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_chatinactivityrequest_analyst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='department',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserOnlineStatus',
        ),
        migrations.RunPython(delete_legacy_departments),
    ]
